image: ubuntu:20.04

before_script:
 - apt-get update -qq
 - export DEBIAN_FRONTEND=noninteractive && apt-get install -y -qq 
    casacore-data casacore-dev 
    cmake
    g++
    git 
    libblas-dev liblapack-dev 
    libboost-filesystem-dev libboost-system-dev libboost-date-time-dev 
    libboost-test-dev 
    libcfitsio-dev 
    libfftw3-dev 
    libgsl-dev 
    libgtkmm-3.0-dev 
    liblua5.3-dev 
    libpng-dev 
    libpython3-dev 
    libxml2-dev 
    pkg-config
    python3
    python3-dev python3-numpy

aoflagger:
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make
    - make install
    - make check
    - cd python
    - echo "import aoflagger"|python3
