#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.15"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    15
#define AOFLAGGER_VERSION_SUBMINOR 0
#define AOFLAGGER_VERSION_DATE_STR "2020-02-20"

#endif
