#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.9.0"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    9
#define AOFLAGGER_VERSION_SUBMINOR 0
#define AOFLAGGER_VERSION_DATE_STR "2016-12-20"

#endif
