#ifndef AOFLAGGER_VERSION_H
#define AOFLAGGER_VERSION_H

#define AOFLAGGER_VERSION_STR      "2.12.0"
#define AOFLAGGER_VERSION_MAJOR    2
#define AOFLAGGER_VERSION_MINOR    12
#define AOFLAGGER_VERSION_SUBMINOR 0
#define AOFLAGGER_VERSION_DATE_STR "2018-09-03"

#endif
